preset:    PSR2
risky:     false
enabled:
  - lowercase_cast
  - include
  - no_extra_consecutive_blank_lines
  - single_quote
  - no_unused_imports
  - no_singleline_whitespace_before_semicolons
  - binary_operator_spaces
  - no_empty_statement
  - no_blank_lines_after_class_opening
  - no_trailing_comma_in_list_call
  - no_leading_namespace_whitespace
  - standardize_not_equals
  - no_trailing_comma_in_singleline_array
  - no_whitespace_in_blank_line
  - whitespace_after_comma_in_array
finder:
  exclude:
    - "vendor"
  name:
    - "*.php"
